/* ═══════════════════════════════════════════
   data.js — Static data store
   All game data + fallback anime data
   ═══════════════════════════════════════════ */

const STEAM_CDN = (id) => `https://cdn.cloudflare.steamstatic.com/steam/apps/${id}/header.jpg`;

const GAMES = [
  {
    id: 'elden-ring-nightreign', category: 'gaming',
    title: 'Elden Ring: Nightreign',
    image: STEAM_CDN(2622380),
    fallbackImage: STEAM_CDN(1245620),
    rating: 9.5, year: 2025, studio: 'FromSoftware',
    platforms: ['PC', 'PS5', 'Xbox Series X'],
    genres: ['Action', 'RPG', 'Co-op'],
    status: 'New',
    description: 'A co-op roguelike experience set in a brand-new nighttime version of the Lands Between. Up to three players fight together through condensed three-day cycles, facing towering Nightlords. It retains the brutal, rewarding combat of Elden Ring but redesigns the entire progression loop for co-op.',
    trailer: 'https://www.youtube.com/watch?v=pFWRpUe2fK0',
    metacritic: 88,
  },
  {
    id: 'black-myth-wukong', category: 'gaming',
    title: 'Black Myth: Wukong',
    image: STEAM_CDN(2358720),
    rating: 9.0, year: 2024, studio: 'Game Science',
    platforms: ['PC', 'PS5'],
    genres: ['Action', 'RPG', 'Mythology'],
    status: 'Hit',
    description: 'A groundbreaking action RPG rooted in Chinese mythology. You play as the Destined One — a monkey warrior who inherits the legacy of the legendary Sun Wukong. With AAA-tier visuals, deep lore drawn from Journey to the West, and punishing but fair combat, it proved Chinese game studios are on the world stage.',
    trailer: 'https://www.youtube.com/watch?v=vEBSB7O9Zes',
    metacritic: 82,
  },
  {
    id: 'baldurs-gate-3', category: 'gaming',
    title: "Baldur's Gate 3",
    image: STEAM_CDN(1086940),
    rating: 9.8, year: 2023, studio: 'Larian Studios',
    platforms: ['PC', 'PS5', 'Xbox'],
    genres: ['RPG', 'Turn-Based', 'Co-op'],
    status: 'GOTY',
    description: "The definitive RPG experience of this generation. Based on D&D 5e rules, BG3 gives you a world that reacts to everything — your choices, your class, your companions, even your face. With over 174 hours of voiced dialogue and virtually infinite replayability, it raised the bar for the entire genre.",
    trailer: 'https://www.youtube.com/watch?v=QaHADbFBkKE',
    metacritic: 96,
  },
  {
    id: 'cyberpunk-2077', category: 'gaming',
    title: 'Cyberpunk 2077',
    image: STEAM_CDN(1091500),
    rating: 8.8, year: 2023, studio: 'CD Projekt Red',
    platforms: ['PC', 'PS5', 'Xbox Series X'],
    genres: ['Action', 'RPG', 'Open World'],
    status: 'Redeemed',
    description: "Night City is one of gaming's greatest open worlds. Post-2.0 patch and Phantom Liberty expansion, Cyberpunk 2077 is the game it always should have been — a dense, emotional, neon-drenched RPG with unmatched atmosphere and a story that will stay with you.",
    trailer: 'https://www.youtube.com/watch?v=8X2kIfS6fb8',
    metacritic: 90,
  },
  {
    id: 'monster-hunter-wilds', category: 'gaming',
    title: 'Monster Hunter Wilds',
    image: STEAM_CDN(2246340),
    rating: 9.2, year: 2025, studio: 'Capcom',
    platforms: ['PC', 'PS5', 'Xbox Series X'],
    genres: ['Action', 'RPG', 'Co-op'],
    status: 'Hot',
    description: 'The most ambitious Monster Hunter yet. Dynamic weather, living ecosystems, and seamless transitions between areas create the most immersive hunting experience in franchise history. Hunt 80+ monsters across the Forbidden Lands with four friends.',
    trailer: 'https://www.youtube.com/watch?v=mNBBMUJmT0c',
    metacritic: 91,
  },
  {
    id: 'lies-of-p', category: 'gaming',
    title: 'Lies of P',
    image: STEAM_CDN(1627720),
    rating: 8.6, year: 2023, studio: 'Round8 Studio',
    platforms: ['PC', 'PS5', 'Xbox'],
    genres: ['Action', 'Souls-like', 'Gothic'],
    status: 'Sleeper Hit',
    description: 'A dark retelling of Pinocchio set in a Belle Époque-inspired city torn apart by a puppet uprising. Polished to a mirror sheen, Lies of P is the best Souls-like not made by FromSoftware — with a satisfying weapon assembly system and one of the best soundtracks in recent memory.',
    trailer: 'https://www.youtube.com/watch?v=fHkc1MIBPqQ',
    metacritic: 80,
  },
  {
    id: 'hades', category: 'gaming',
    title: 'Hades',
    image: STEAM_CDN(1145360),
    rating: 9.3, year: 2020, studio: 'Supergiant Games',
    platforms: ['PC', 'PS4/5', 'Switch', 'Xbox'],
    genres: ['Roguelike', 'Action', 'Story-Rich'],
    status: 'Classic',
    description: 'The game that proved roguelikes can have incredible stories. Play as Zagreus, son of Hades, escaping the Underworld run by run. Each death reveals more story, more lore, more character. The best narrative design in any roguelike, period — and the combat is razor-sharp.',
    trailer: 'https://www.youtube.com/watch?v=91t0ha9x0AE',
    metacritic: 93,
  },
  {
    id: 'god-of-war-pc', category: 'gaming',
    title: 'God of War',
    image: STEAM_CDN(1593500),
    rating: 9.4, year: 2022, studio: 'Santa Monica Studio',
    platforms: ['PC', 'PS4', 'PS5'],
    genres: ['Action', 'Adventure', 'Story-Rich'],
    status: 'Must Play',
    description: "Kratos and Atreus's journey through Norse mythology is one of gaming's greatest father-son stories. Stunning visuals shot in a single take, emotional depth that will surprise you, and satisfying axe combat make this an essential experience for anyone who calls themselves a gamer.",
    trailer: 'https://www.youtube.com/watch?v=K0u_kAWLJOA',
    metacritic: 94,
  },
  {
    id: 'sekiro', category: 'gaming',
    title: 'Sekiro: Shadows Die Twice',
    image: STEAM_CDN(814380),
    rating: 9.1, year: 2019, studio: 'FromSoftware',
    platforms: ['PC', 'PS4', 'Xbox One'],
    genres: ['Action', 'Stealth', 'Samurai'],
    status: 'Masterpiece',
    description: "FromSoftware's most precise, demanding, and rewarding game. Set in a fantastical version of Sengoku-era Japan, you play as a shinobi seeking revenge. The posture system is genius — duels feel like real sword fights, and mastering it feels better than almost anything else in gaming.",
    trailer: 'https://www.youtube.com/watch?v=rXMX4YJ7Lks',
    metacritic: 90,
  },
  {
    id: 'persona-5-royal', category: 'gaming',
    title: 'Persona 5 Royal',
    image: STEAM_CDN(1687950),
    rating: 9.5, year: 2022, studio: 'Atlus',
    platforms: ['PC', 'PS4/5', 'Switch', 'Xbox'],
    genres: ['JRPG', 'Turn-Based', 'Social Sim'],
    status: 'Legendary',
    description: "The most stylish JRPG ever made. Persona 5 Royal combines a sharp turn-based battle system with a deep social simulation, wrapped in an unforgettable aesthetic. 100+ hours of content, a phenomenal jazz/funk soundtrack, and a story about rebelling against corrupt society.",
    trailer: 'https://www.youtube.com/watch?v=kBBQyXKKQWE',
    metacritic: 95,
  },
  {
    id: 'witcher-3', category: 'gaming',
    title: 'The Witcher 3: Wild Hunt',
    image: STEAM_CDN(292030),
    rating: 9.6, year: 2015, studio: 'CD Projekt Red',
    platforms: ['PC', 'PS4/5', 'Switch', 'Xbox'],
    genres: ['RPG', 'Open World', 'Fantasy'],
    status: 'All-Time Great',
    description: "Arguably the greatest open-world RPG ever made. Geralt's quest to find his adopted daughter Ciri takes you across a breathtaking world filled with moral grey areas, unforgettable characters, and side quests that are better than most games' main stories. Two decades later, still unmatched.",
    trailer: 'https://www.youtube.com/watch?v=c0i88t0Kacs',
    metacritic: 92,
  },
  {
    id: 'hollow-knight', category: 'gaming',
    title: 'Hollow Knight',
    image: STEAM_CDN(367520),
    rating: 9.2, year: 2017, studio: 'Team Cherry',
    platforms: ['PC', 'PS4/5', 'Switch', 'Xbox'],
    genres: ['Metroidvania', 'Action', 'Platformer'],
    status: 'Indie Gem',
    description: "A hauntingly beautiful Metroidvania set in a vast underground kingdom of insects. Hand-drawn art, a melancholic atmosphere, tight nail-sword combat, and one of the most rewarding exploration loops in gaming history — all made by just 3 people. Hollow Knight is a miracle.",
    trailer: 'https://www.youtube.com/watch?v=UAO2urG23S4',
    metacritic: 87,
  },
];

// Fallback anime data (used if Jikan API is rate-limited)
const ANIME_FALLBACK = [
  {
    id: 'frieren', category: 'anime',
    title: 'Frieren: Beyond Journey\'s End',
    image: 'https://cdn.myanimelist.net/images/anime/1015/138006.jpg',
    rating: 9.4, year: 2023, studio: 'Madhouse',
    episodes: 28, status: 'Finished',
    genres: ['Adventure', 'Drama', 'Fantasy'],
    description: 'After the demon king is defeated, the elven mage Frieren embarks on a journey of self-discovery. Her long elven lifespan means she outlives her human companions — and only later realizes she never truly knew them. A meditation on time, memory, and what it means to live.',
    trailer: 'https://www.youtube.com/watch?v=UYBCkHGqKKA',
  },
  {
    id: 'demon-slayer-s4', category: 'anime',
    title: 'Demon Slayer: Hashira Training Arc',
    image: 'https://cdn.myanimelist.net/images/anime/1286/99889.jpg',
    rating: 9.2, year: 2024, studio: 'ufotable',
    episodes: 8, status: 'Finished',
    genres: ['Action', 'Fantasy', 'Supernatural'],
    description: 'Tanjiro and the Demon Slayer Corps undergo brutal Hashira training to prepare for their final battle with Muzan Kibutsuji. ufotable\'s animation continues to push the limits of what TV anime can look like, and the emotional stakes have never been higher.',
    trailer: 'https://www.youtube.com/watch?v=QFy3kJ5_Gj0',
  },
  {
    id: 'jjk-s3', category: 'anime',
    title: 'Jujutsu Kaisen Season 3',
    image: 'https://cdn.myanimelist.net/images/anime/1171/109222.jpg',
    rating: 9.4, year: 2024, studio: 'MAPPA',
    episodes: 21, status: 'Finished',
    genres: ['Action', 'Supernatural', 'Dark Fantasy'],
    description: 'The Culling Game arc reaches its climax. Yuji and his allies navigate a deadly death game devised by Kenjaku while confronting the true nature of jujutsu sorcery. MAPPA delivers some of the most intense action sequences in anime history.',
    trailer: 'https://www.youtube.com/watch?v=lh9tUtFpN4U',
  },
  {
    id: 'solo-leveling', category: 'anime',
    title: 'Solo Leveling',
    image: 'https://cdn.myanimelist.net/images/anime/1823/138942.jpg',
    rating: 8.8, year: 2024, studio: 'A-1 Pictures',
    episodes: 12, status: 'Finished',
    genres: ['Action', 'Fantasy', 'Isekai'],
    description: 'Sung Jinwoo, the weakest hunter in the world, gains the unique ability to level up in a world where hunters cannot grow stronger. A classic power fantasy done right — gorgeous fight animation, satisfying progression, and a protagonist who earns every power-up.',
    trailer: 'https://www.youtube.com/watch?v=PR4zECBFGJ4',
  },
  {
    id: 'blue-lock', category: 'anime',
    title: 'Blue Lock Season 2',
    image: 'https://cdn.myanimelist.net/images/anime/1719/136083.jpg',
    rating: 8.7, year: 2024, studio: '8bit',
    episodes: 13, status: 'Airing',
    genres: ['Sports', 'Psychological', 'Action'],
    description: 'The Blue Lock project continues as Isagi Yoichi refines his ego and spatial awareness to become the world\'s greatest striker. The psychological depth and football strategy make this the most electrifying sports anime since Haikyuu.',
    trailer: 'https://www.youtube.com/watch?v=R4t_TQxH2AE',
  },
  {
    id: 'dandadan', category: 'anime',
    title: 'DAN DA DAN',
    image: 'https://cdn.myanimelist.net/images/anime/1439/142881.jpg',
    rating: 8.9, year: 2024, studio: 'Science SARU',
    episodes: 12, status: 'Finished',
    genres: ['Action', 'Comedy', 'Supernatural', 'Romance'],
    description: 'Momo believes in ghosts but not aliens. Okarun believes in aliens but not ghosts. When they both turn out to be right, chaos ensues. Science SARU\'s animation is absolutely wild — fast, expressive, and unlike anything else. The most fun anime of 2024.',
    trailer: 'https://www.youtube.com/watch?v=NcN9ztj_6kk',
  },
];

// Config constants
const CONFIG = {
  JIKAN_API: 'https://api.jikan.moe/v4',
  ITEMS_PER_PAGE: 6,
  DEBOUNCE_MS: 250,
};
